[package]
name = "io-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true  


[dependencies]
rand ="0.8.5"
sysfs_gpio = { version = "0.6", features = ["async-tokio"] }
tokio = { version = "1.35.1", features = ["full"] }
futures = { version = "0.3.30" }

dbus = "0.9.7"
libc = "0.2.69"
dbus-tokio = "0.7.6"

lumi-utils = {path = "../cores/lumi-utils"}
message = {path = "../cores/message"}
clap = {version = "4.4.11", features = ["derive", "env"]}
log = "0.4.20"
env_logger = { version = "0.11.2" }
async-trait = "0.1.75"
rumqttc = "0.23.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
libdbus-sys = { version = "0.2.5", features = ["vendored"] }
